version: '3.9'
services:
  selenium:
    image: "selenium/standalone-firefox"
    ports:
      - "4444:4444"
  redis:
    image: "redis"
  api:
    build: ./api
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - selenium



